---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: hello_hapi1
  - name: dependency-cache

run:
  path: hello_hapi1/ci/scripts/run_tests.sh
